services:
  # Backend Service
  - type: web
    name: coulouche-bot-backend
    runtime: node
    buildCommand: |
      cd backend
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: CLE_API
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://chatbot-wrwo.onrender.com
      - key: PORT
        value: "10000"

  # Frontend Service
  - type: static
    name: coulouche-bot-frontend
    runtime: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    publishDir: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://coulouche-bot-backend.onrender.com/api/chat/message/

databases:
  - name: coulouche-bot-db
    databaseName: coulouche_bot
    user: coulouche_user
    plan: free
